language: r

sudo: false

cache: packages

r: bioc-devel
bioc_check: true

warnings_are_errors: false

branches:
  only:
    - master
    - RELEASE_3_7

r_packages:
  - rlang
  - dplyr
  - magrittr
  - ggplot2
  - covr

bioc_packages:
  - BiocGenerics
  - BiocCheck
  - S4Vectors
  - GenomicRanges
  - IRanges
  - BiocStyle
  - HelloRanges
  - HelloRangesData
  - BSgenome.Hsapiens.UCSC.hg19


after_success:
  - Rscript -e 'library(covr);codecov()'