language: r

sudo: false

cache: packages

r: bioc-devel
bioc_check: true

warnings_are_errors: false

branches:
  only:
    - master
    - RELEASE_3_8

r_packages:
  - rlang
  - dplyr
  - magrittr
  - ggplot2
  - covr

bioc_packages:
  - BiocGenerics
  - BiocCheck
  - S4Vectors
  - GenomicRanges
  - IRanges
  - BiocStyle
  - HelloRanges
  - HelloRangesData
  - BSgenome.Hsapiens.UCSC.hg19
  - rtracklayer


after_success:
  - Rscript -e 'library(covr);codecov()'
  
before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true