warnings_are_errors: false

language: r

cache: packages

sudo: false

r:
  - bioc-release
  - bioc-devel

bioc_packages:
  - HelloRanges
  - HelloRangesData
  - BSgenome.Hsapiens.UCSC.hg19
  - ggbio
  - biovizBase

r_packages:
  - rlang
  - dplyr
  - Hmisc
  - magrittr
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
